name: Deploy to Azure Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  DeployAzureStack:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.0

      - name: Deploy Azure Stack
        uses: ./.github/actions/deploy
        with:
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          bicepFilePath: "./template.bicep"
          stackName: ${{ github.event.repository.name }}
          stackResourceGroup: ${{ vars.STACK_RESOURCE_GROUP }}
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
