name: Deploy Infrastructure to Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.0

      - name: Deploy Azure Stack
        uses: ./.github/actions/deploy
        with:
          azureTenantId: ${{ secrets.AZURE_TENANT_ID }}
          azureClientId: ${{ secrets.AZURE_CLIENT_ID }}
          azureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          bicepFilePath: "./template.bicep"
          stackName: "my-stack"
          stackEnv: "dev"
          stackResourceGroup: "DevRG"
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
